config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :issues do
      post 'issues/add_members'
      post 'issues/complete'
      get 'issues/show_members'
      get 'issues/processing'
      post 'issues/remove_members'
      get 'issues/reopen'
    end
    collection do
      get 'show_members'
      post 'remove_members'
    end
  end
  
  post 'projects/add_members'

  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root :to => 'projects#index'
    end
    unauthenticated :user do
      root :to => 'projects#home', as: :unauthenticated_root
    end
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :project
  enum status: [:pending, :processing, :completed]
  enum priority: [:Low, :Normal, :High]
  has_many :user_issues
  has_many :users, through: :user_issues
  validates :title, :description, :deadline, :priority, :presence => true 


end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @issue = Issue.new
  end

  def edit
  end

  def update
  end

  def destroy
    project = Project.find(params[:project_id])
    issue = Issue.find(params[:id])
    users = issue.users
    if users.present?
      members = UserIssue.where(:issue_id => issue.id)
      members.destroy_all
    end
    if issue.destroy
      flash[:notice] = "Succeessfully Deleted"
    else
      flash[:notice] = "Could not Delete the Isse"
    end
    redirect_to project_path(project.id)
  end

  def create
    @project = Project.find(params[:project_id])
    @issue = Issue.new(set_params)
    @issue.project_id = @project.id
    @issue.status = 0
    if @issue.save
      flash[:notice] = "Issue successfully created"
    else
      flash[:notice] = "Issue was not created"
    end
    redirect_to project_path(@project.id)
  end

  def show_members
    @project = Project.find(params[:project_id])
    @users = @project.users
    @issue = Issue.find(params[:issue_id])
    @members = @issue.users
  end

  def add_members
    ids = params[:user_ids]
    project_id = params[:project_id]
    @issue = Issue.find(params[:issue_id])
    if ids.present?
      ids.each do|id|
        if UserIssue.where(:user_id => id, :issue_id => @issue.id).blank?
           if UserIssue.create(:user_id => id, :issue_id => @issue.id)
            flash[:notice] = "Succeessfully added the members"
          else
            flash[:alert] = "Could not add the members"
          end
        else 
          flash[:alert] = "Slected member is already assigned to the project."
        end
      end
      redirect_to project_path(project_id)
    else
      flash[:notice] = "Please select at least one member"
      redirect_to project_issue_issues_show_members_path(project_id, @issue.id)
    end
  end

  def remove_members
    ids = params[:user_ids]
    @issue = Issue.find(params[:issue_id])
    project_id = params[:project_id]
    if ids.present?
      ids.each do |i|
        user = UserIssue.where(:user_id => i, :issue_id => @issue.id)
        if user.first.destroy
          flash[:notice] = "Succeessfully Removed"
        else
          flash[:notice] = "Could not Delete the user"
        end
      end
    else
     flash[:notice] = "Please select atleast one member"
    end
     redirect_to project_issue_issues_show_members_path(project_id, @issue.id)
  end

  def complete
    @issue = Issue.find(params[:issue_id])
    @issue.completed!
    redirect_to project_path(@issue.project_id)  
  end

  def processing
    @issue = Issue.find(params[:issue_id])
    @issue.processing!
    redirect_to project_path(@issue.project_id)
  end

  def reopen
    @issue = Issue.find(params[:issue_id])
    @issue.pending!
    redirect_to project_path(@issue.project_id)
  end

  private
  def set_params
    params.require(:issue).permit(:title, :description, :deadline, :priority, :status)
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
	
	
end

app/views/issues/_issue.html.erb
<%= form_for [@project, @issue] do |p|%>
	<div class = "form">
		<div class = "project">
			<h3>Add New Issue</h3>
			<ul>
		    <% @issue.errors.full_messages.each do |error| %>
		    <li><%= error %></li>
		    <% end %>
		  </ul>
		  <div class = "form-group">
			  <p>
			  	<%= p.label :title, class: "form-label" %><br/>
			    <%= p.text_field :title, class: "form-control", :required => true%>
			  </p>
			</div>
			<div>
			  <p>
			  	<%= p.label :description, class: "form-label" %><br/>
			    <%= p.text_area :description, class: "form-control" %>
			  </p>
			</div>
			<div>
			  <p>
			  	<%= p.label :deadline, class: "form-label" %>
			    <%= p.text_field :deadline, class: "form-control", class: "datepicker"%>
			  </p>
			</div>
			<div class = "form-group">
			  <p>
			  	<%= p.label :priority, class: "form-label" %>
			  	<%= p.select(:priority, options_for_select([["High", "High"], ["Normal", "Normal"], ["Low", "Low"]])) %>
			  </p>
			</div>
			<div class = "form-group">
				<p>
					<%= p.submit %>
				</p>
			</div>
			<%= link_to "Back To Project", project_path(@project.id), class: "btn btn-primary"%>
		</div>
	</div>
<% end %>

app/views/issues/create.html.erb
<h1>Issues#create</h1>
<p>Find me in app/views/issues/create.html.erb</p>

app/views/issues/destroy.html.erb
<h1>Issues#destroy</h1>
<p>Find me in app/views/issues/destroy.html.erb</p>

app/views/issues/edit.html.erb
<h1>Issues#edit</h1>
<p>Find me in app/views/issues/edit.html.erb</p>

app/views/issues/index.html.erb
<h1>Issues#index</h1>
<p>Find me in app/views/issues/index.html.erb</p>

app/views/issues/new.html.erb
<%= render 'issue'%>

app/views/issues/show_members.html.erb
<div class = "available-user">
	<div class = "row">
		<div class = "col-sm-6">
			<h2>Available users</h2>
			<%= form_tag project_issue_issues_add_members_path(@project.id, @issue.id) do%>
				<table class = "table table-hover">
					<tbody>
						<% @users.each do |u| %>
						<tr>
							<td><%= check_box_tag "user_ids[]", u.id, false, :disabled=>is_assigned_to_issue(@issue, u.id)%>
							<%= u.email %><td>
						<% end %>
						</tr>
						<tr>
							<td><%= submit_tag ("add selected members")%></td>
						</tr>
					</tbody>
				</table>
			<% end %>
			<%= link_to "Back To Project", project_path(@project.id), class: "btn btn-primary"%>
		</div>
		<div class = "col-sm-6">
			<h2>Assigned Members</h2>
			<% if @members.present?%>
				<%= form_tag project_issue_issues_remove_members_path(@project.id, @issue.id) do%>
					<table class = "table table-hover">
						<tbody>
							<% @members.each do |m|%>
							<tr>
								<td><%= check_box_tag "user_ids[]", m.id%>
									<%= m.email %></td>
							<% end %>
							</tr>
							<tr>
								<td><%= submit_tag ("Remove selected members")%></td>
							</tr>
						</tbody>
					</table>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/issues/update.html.erb
<h1>Issues#update</h1>
<p>Find me in app/views/issues/update.html.erb</p>