config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :issues do
      post 'issues/add_members'
      post 'issues/complete'
      get 'issues/show_members'
      get 'issues/processing'
      post 'issues/remove_members'
      get 'issues/reopen'
    end
    collection do
      get 'show_members'
      post 'remove_members'
    end
  end
  
  post 'projects/add_members'

  devise_for :users
  
  devise_scope :user do
    authenticated :user do
      root :to => 'projects#index'
    end
    unauthenticated :user do
      root :to => 'projects#home', as: :unauthenticated_root
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :project_name, presence: true
	has_many :assignments
	has_many :users, through: :assignments
	has_many :issues
	validates :project_name, :start_date, :target_end_date, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, :except => [:home]
  
  def index
    @assigned_projects = current_user.projects
    @projects = Project.where(:created_by => current_user.id)
    @current_user_projects = current_user.projects
  end

  def show
    @project = Project.find(params[:id])
    @members = @project.users
    @issue = @project.issues.order(:status, created_at: :desc)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.start_date = params["project"][:start_date]
    @project.target_end_date = params["project"][:target_end_date]
    @project.final_end_date = params["project"][:final_end_date]
    @project.created_by = current_user.id
    if @project.save
      flash[:notice] = "Project successfully created"
    else
      flash[:notice] = "Project cannot be created"
    end
    redirect_to projects_path
  end

  def edit
    @project = Project.find(params[:id])
  end

  def destroy
    project = Project.find(params[:id])
    users = project.users
    if users.present?
      members = Assignment.where(:project_id => project.id)
      members.destroy_all
    end
    if project.destroy
      flash[:notice] = "successfully deleted"
    else
      flash[:notice] = "Could not delete the project"
    end
    redirect_to projects_path
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Succeessfully Updated"
      redirect_to projects_path
    else
      flash[:alert] = "Sorry the update failed"
      redirect_to projects_path
    end
  end

  def show_members
    @users = User.all
    @project = Project.find(params[:project_id])
    @members = @project.users
  end

  def add_members
    ids = params[:user_ids]
    project_id = params[:project_id]
    if ids.present?
      ids.each do|id|
        if Assignment.where(:user_id => id, :project_id => project_id).blank?
           if Assignment.create(:user_id => id, :project_id => project_id)
            flash[:notice] = "Succeessfully added the members"
          else
            flash[:alert] = "Could not add the members"
          end
        else 
          flash[:alert] = "Slected member is already assigned to the project."
        end
      end
      redirect_to projects_path
    else
      flash[:notice] = "Please select at least one member"
      redirect_to show_members_projects_path(:project_id => project_id)
    end
  end

  def remove_members
    ids = params[:user_ids]
    project_id = params[:project_id]
    if ids.present?
      ids.each do |i|
        user = Assignment.where(:user_id => i, :project_id => project_id)
        if user.first.destroy
          flash[:notice] = "Succeessfully Removed!!!"
        else
          flash[:alert] = "Could not remove the user"
        end
        redirect_to show_members_projects_path(:project_id => project_id)
      end
    end
  end

  def home 
  end

  private
  def project_params
    params.require(:project).permit(:project_name, :start_date, :target_end_date, :final_end_date)
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def created_by project
		project.created_by == current_user.id.to_s
	end
	
	def is_onprocess issue
		issue.status == "processing"		
	end

	def is_pending issue
		issue.status == "pending"
	end
	def is_complete issue
		issue.status == "completed"
		
	end

	def is_assigned issue
		if issue.users.present?
			users = issue.users
			users.each do|u|
				 u.id == current_user.id
			end
		else
			return false
		end
	end

	def date date
		if date.present?
			date.to_date.to_formatted_s(:long_ordinal)
		end
	end

	def is_assigned_to_project project, user_id
		user = Assignment.where(:user_id => user_id, :project_id => project.id)
		user.present?
	end
end

app/views/projects/_project.html.erb
<%= form_for [@project] do |p|%>
	<div class = "form">
		<div class="project">
			<ul>
		    <% @project.errors.full_messages.each do |error| %>
		    <li><%= error %></li>
		    <% end %>
		  </ul>
		  <div class = "form-group">
			  <p>
			  	<%= p.label :Project_name, class: "form-label" %><br/>
			    <%= p.text_field :project_name, class: "form-control", :required => true%>
			  </p>
			</div>
			<div class = "form-group">
			  <p>
			  	<%= p.label :Start_date, class: "form-label" %><br/>
			    <%= p.text_field :start_date, class: "form-control", class: "datepicker"%>
			  </p>
			</div>
			<div class = "form-group">
			  <p>
			  	<%= p.label :Target_end_date, class: "form-label" %><br/>
			    <%= p.text_field :target_end_date, class: "form-control", class: "datepicker"%>
			  </p>
			</div>
			<div class = "form-group">
			  <p>
			  	<%= p.label :final_end_date, class: "form-label" %><br/>
			    <%= p.text_field :final_end_date, class: "form-control", class: "datepicker"%>
			  </p>
			</div>
			<div class = "form-group">
				<p>
					<%= p.submit %>
				</p>
			</div> <br>
			<%= link_to "Back To Projects", projects_path, class: "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<div class = "issue"><h3>Edit Project</h3></div>
<%= render 'project' %>

app/views/projects/home.html.erb
<div class = "homepage">
  <div class = "container-fluid">
  <div class = "col-sm-6">
    <%= image_tag("issue.jpg", width:"629", height:"500")%>
  </div>
  <div class = "col-sm-6">
    
     <%= render 'devise/sessions/new'%>
     <%= render 'devise/registrations/new' %>
    </div>
  </div>
<div>

app/views/projects/index.html.erb
<div class = "container-fluid">
	<%= link_to "Create New Project", new_project_path, class: "btn btn-primary"%>
	<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal-<%= current_user.id%>">View Tasks</button>
	<div class = "row">
		<% if @projects.present? %>
			<div class = "issue"><h3>Your Projects</h3></div>
			<% @projects.each do |p| %>
				<div class = "col-sm-4">
					<table class="table table-hover project">
					
						<thead>
							<tr>
							<th>Name: <%= p.project_name %></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Start Date: <%= date(p.start_date) %></td>
							</tr>
							<tr>
								<td>Target Date: <%= date(p.target_end_date) %></td>
							</tr>
							<tr>
								<td>End Date: <%= date(p.final_end_date) %></td>
							</tr>
							<tr>
								<td>Assigned Members: <%= p.users.count%></td>
							</tr>
							<tr>
								<td><%= link_to "View Details", project_path(p.id), class: "btn btn-primary"%>
								<%= link_to "Delete", project_path(p.id),  class: "btn btn-primary", method: :delete, data: {confirm: "Really delete the post?"} %>
								<%= link_to "Add Member", show_members_projects_path( :project_id => p.id), class: "btn btn-primary"%></td>
							</tr>
						</tbody>
					</table>
				</div>
			<% end %>
		<% end %>
	</div>
	<div class = "row">
		<% if @assigned_projects.present? %>
			<div class = "issue"><h3>Assigned Projects</h3></div>
			<% @assigned_projects.each do |p| %>
				<div class = "col-sm-4">
					<table class="table table-hover project">
						<thead>
							<tr>
							<th>Name: <%= p.project_name %></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Start Date: <%= date(p.start_date) %></td>
							</tr>
							<tr>
								<td>Target Date: <%= date(p.target_end_date) %></td>
							</tr>
							<tr>
								<td>End Date: <%= date(p.final_end_date) %></td>
							</tr>
							<tr>
								<td>Assigned Members: <%= p.users.count%></td>
							</tr>
							<tr>
								<td><%= link_to "View Details", project_path(p.id), class: "btn btn-primary"%>
							</tr>
						</tbody>
					</table>
				</div>
			<% end %>
		<% end %>
	</div>
</div>
<div id="myModal-<%=current_user.id%>" class="modal fade" role="dialog">
  <div class="modal-dialog">
  	<div class = "project">
	    <!-- Modal content-->
	    <div class="modal-content">
	      <div class="modal-header issue">
	        <h4 class="modal-title ">Assigned Tasks</h4>
	      </div>
	      <div class="modal-body">
	      	<table class = "table table-hover">
	    			<thead>
	      			<tr class = "success">
	      				<th>Project Name</th>
	      				<th>Issue Title</th>
	      				<th>Issue Status</th>
	      				<th>Issue Deadline</th>
	      			</tr>
	    			</thead>
	        	<% @current_user_projects.each do|t|%>
	    				<% t.issues.each do |i|%>
	    					<% if is_assigned(i)%>
		        			<tbody>
		        				<tr class = "success">
			        				<td><%= link_to i.project.project_name, project_path(i.project_id)%></td>
			        				<td><%= i.title %></td>
			        			  <td><%= i.status %></td>
			        			  <td> <%= i.deadline %></td>
			        			</tr>
	    						<% end %>
	    						</tbody>
	    				<% end %>
		       	<% end %>
		      </table>
		    </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class = "issue"><h3>Add New Project</h3></div>
<%= render 'project' %>

app/views/projects/show.html.erb
<div class = "container-fluid">
	<div class = "row">
		<div class = "col-sm-6">
			<table class="table table-hover project">
				<thead>
					<tr>
					<th>Name: <%= @project.project_name %></th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Start Date: <%= date(@project.start_date) %></td>
					</tr>
					<tr>
						<td>Target Date: <%= date(@project.target_end_date) %></td>
					</tr>
					<tr>
						<td>End Date: <%= date(@project.final_end_date) %></td>
					</tr>
					<tr>
						<td>Number of Assigned Members: <%= @members.count%></td>
					</tr>
					<tr>
						<td><% if @project.created_by == current_user.id.to_s %>
							<%= link_to "Edit", edit_project_path(@project.id), class: "btn btn-primary"%>
							<% end %>
							<%= link_to "Add Issue", new_project_issue_path(@project.id), class: "btn btn-primary"%>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class = "col-sm-6">
			<table class = "table table-hover">
				<thead>
					<tr class = "success">
						<th>Project Members</th>
					</tr>
				</thead>
				<tbody>
					<% @members.each do |i| %>
						<tr class = "success">
							<td><%= i.email%></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div class = "row">
		<div class = "issue"><h3>Project Issues</h3></div>
		<div class = "col-sm-12">
			<table class = "table table-hover project">
				<thead>
					<tr>
						<th>Title</th>
						<th>Deadline</th>
						<th>Priority</th>
						<th>Status</th>
						<th>Assigned To</th>
						<th>Assign/Remove</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @issue.each do |i| %>
						<tr>
							<td><%= i.title%></td>
							<td><%= i.deadline%></td>
							<td><%= i.priority%></td>
							<td><%= i.status%><br>
									<% if is_onprocess(i) and is_assigned(i)%>
										<%= link_to "set complete",project_issue_issues_complete_path(@project.id, i.id), method: :post, data: {:confirm=> "Are you sure?"}%>
									<% end %>
									<% if is_pending(i) and is_assigned_to_issue(i, current_user.id)%>
										<%= link_to "set processing",project_issue_issues_processing_path(@project.id, i.id), method: :post, data: {:confirm=> "Are you sure?"}%>
									<%end%>
									<% if is_complete(i) and created_by(@project)%>
										<%= link_to "Reopen?",project_issue_issues_reopen_path(@project.id, i.id), method: :post, data: {:confirm=> "Are you sure?"}%>
									<% end %>
							</td>
							<td><p><%= i.users.count%> Members</p></td>
							<td><% if created_by(@project)%>
									<%= link_to "Assign/Remove", project_issue_issues_show_members_path( :project_id => i.project_id, :issue_id => i.id), class: "btn btn-primary"%>
									<% end %>
							</td>
							<td><% if created_by(@project) %>
									<%= link_to "Delete", project_issue_path(@project.id, i.id), class: "btn btn-primary", method: :delete, data: {:confirm=> "Are you sure?"}%></td>
									<% end %>
							<td><button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal-<%= i.id%>">View Details</button></td>
						</tr>
						<tr><!-- Modal -->
						<div id="myModal-<%=i.id%>" class="modal fade" role="dialog">
						  <div class="modal-dialog">

						    <!-- Modal content-->
						    <div class="modal-content">
						      <div class="modal-header">
						        <h4 class="modal-title"><%= i.title %></h4>
						      </div>
						      <div class="modal-body">
						        <p><%= i.description%></p>
						        <p> Assigned To: 
						        	<% i.users.each do|u|%></p>
							        <p><%= u.email%></p>
							       	<% end %>
							      <p>Status: <%= i.status%></p>
							      <p>Priority: <%= i.priority%></p>
							      <p>Deadline: <%= i.deadline%></p>
							      </p>
						      </div>
						      <div class="modal-footer">
						        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						      </div>
						    </div>

						  </div>
						</div>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/projects/show_members.html.erb
<div class = "available-user">
	<div class = "row">
		<div class = "col-sm-6">
			<h2>Available users</h2>
			<%= form_tag projects_add_members_path, method: :post do%>
				<table class = "table table-hover">
					<tbody>
						<% @users.each do |u| %>
							<tr>
								<td><%= check_box_tag "user_ids[]", u.id, false, :disabled=>is_assigned_to_project(@project, u.id)%>
								<%= u.email %></td>
							</tr>
						<% end %>
						<%= hidden_field_tag "project_id", @project.id%>
						<tr>
							<td><%= submit_tag ("Assign selected members")%></td>
						</tr>
					</tbody>
				</table>
			<% end %><br>
			<%= link_to "Back To Projects", projects_path, class: "btn btn-primary"%>
		</div>
		<div class = "col-sm-6">
			<h2>Project Members</h2>
			<% if @members.present? %>
					<%= form_tag remove_members_projects_path( :project_id => @project.id) do%>
					<table class = "table table-hover">
						<tbody>
							<tr>
								<% @members.each do|u| %>
									<td><%= check_box_tag "user_ids[]", u.id%>
									<%= u.email%></td>
							</tr>
							<% end %>
							<%= hidden_field_tag "project_id", @project.id%>
							<tr>
							<td><%= submit_tag ("Remove selected members")%></td>
						</tr>
						</tbody>
					</table>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>